### ISSUE TITLE
Common service configuration stuff

### ISSUE THREAD

**Issue by mookerji** [swift-nav/skylark-core#2]
Context: question came up while doing configuration stuff for logging and monitoring.

Currently, our configuration stuff is spread out and replicated between our various services. We'd like to have an extensible, uniform interface for service defaults, configuration files, and command-line overrides and provide this in the core library.

@mfine @JoshuaGross

**Comment by JoshuaGross** [comment]
Maybe we could define a super-simple interface on top of `convox env`. We can come up with a scheme for consistent naming of configurations in the `env` across all services and using a simple CLI tool to audit and do updates. Thoughts?

**Comment by mookerji** [comment]
Closed by #3 .
