### ISSUE TITLE
Look into Bytestring Builders for improving text logging performance

### ISSUE THREAD

**Issue by mookerji** [swift-nav/skylark-core#20]
A note in case it becomes an issue later: not clear to me yet if the way we're doing text output is super-efficient. For example, see: https://github.com/swift-nav/skylark-core/blob/master/src/Network/Skylark/Core/Trace.hs#L58

**Comment by mfine** [comment]
The [monad-logger](http://haddock.stackage.org/lts-4.2/monad-logger-0.3.17) routines take `Text`. The `formatting` package is built on top of `text-format` and use text builders. See a post on formatting [here](http://chrisdone.com/posts/formatting). It so far has offered a nice abstraction over using builders directly.
